-- 0003_reporting.sql
-- Report categories, reports, attachments, updates, status history.
-- Status model per CLAUDE.md: new, triaged, in_progress, resolved, rejected, needs_more_info.

set search_path = public;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'report_status') then
    create type report_status as enum (
      'new', 'triaged', 'in_progress', 'resolved', 'rejected', 'needs_more_info'
    );
  end if;
end$$;

-- =====================================================================
-- Categories (seeded with 4 minimums per CLAUDE.md)
-- =====================================================================

create table if not exists report_categories (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,                -- 'service' | 'security' | 'environment' | 'other'
  sort_order int not null default 0,
  is_active boolean not null default true,
  -- sla_hours: TBD per category in decision-log; nullable until policy chốt.
  sla_hours int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger report_categories_set_updated_at
before update on report_categories
for each row execute function set_updated_at();

create table if not exists report_category_translations (
  category_id uuid not null references report_categories(id) on delete cascade,
  locale locale_code not null,
  name text not null,
  primary key (category_id, locale)
);

-- =====================================================================
-- Reports
-- =====================================================================

create table if not exists reports (
  id uuid primary key default gen_random_uuid(),
  -- Public-facing short code shown to user (e.g. NBD-2026-000123); generated by app/trigger.
  code text unique,
  reporter_id uuid references app_users(id) on delete set null,
  category_id uuid references report_categories(id) on delete restrict,
  description text not null,
  location_text text,
  latitude double precision,
  longitude double precision,
  status report_status not null default 'new',
  assignee_admin_id uuid references admin_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger reports_set_updated_at
before update on reports
for each row execute function set_updated_at();

create index if not exists reports_reporter_idx on reports(reporter_id);
create index if not exists reports_status_idx on reports(status);
create index if not exists reports_category_idx on reports(category_id);
create index if not exists reports_created_at_idx on reports(created_at desc);

-- =====================================================================
-- Attachments (media references — actual files in object storage)
-- =====================================================================

create table if not exists report_attachments (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references reports(id) on delete cascade,
  storage_path text not null,                -- path in supabase storage bucket
  media_type text not null check (media_type in ('image', 'video', 'audio', 'doc')),
  byte_size bigint,
  created_at timestamptz not null default now()
);

create index if not exists report_attachments_report_idx on report_attachments(report_id);

-- =====================================================================
-- Updates (admin response messages visible to user)
-- =====================================================================

create table if not exists report_updates (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references reports(id) on delete cascade,
  author_admin_id uuid references admin_users(id) on delete set null,
  body text not null,
  is_visible_to_user boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists report_updates_report_idx on report_updates(report_id);

-- =====================================================================
-- Status history (audit trail of status changes)
-- =====================================================================

create table if not exists report_status_history (
  id uuid primary key default gen_random_uuid(),
  report_id uuid not null references reports(id) on delete cascade,
  from_status report_status,
  to_status report_status not null,
  changed_by_admin_id uuid references admin_users(id) on delete set null,
  note text,
  changed_at timestamptz not null default now()
);

create index if not exists report_status_history_report_idx on report_status_history(report_id);

-- Auto-record status transitions
create or replace function record_report_status_change()
returns trigger
language plpgsql
as $$
begin
  if (tg_op = 'INSERT') then
    insert into report_status_history (report_id, from_status, to_status)
    values (new.id, null, new.status);
  elsif (tg_op = 'UPDATE' and new.status is distinct from old.status) then
    insert into report_status_history (report_id, from_status, to_status, changed_by_admin_id)
    values (new.id, old.status, new.status, new.assignee_admin_id);
  end if;
  return new;
end;
$$;

create trigger reports_status_history
after insert or update of status on reports
for each row execute function record_report_status_change();

-- =====================================================================
-- RLS
-- =====================================================================

alter table report_categories             enable row level security;
alter table report_category_translations  enable row level security;
alter table reports                       enable row level security;
alter table report_attachments            enable row level security;
alter table report_updates                enable row level security;
alter table report_status_history         enable row level security;

create policy report_categories_public_read on report_categories
for select using (is_active);

create policy report_category_translations_public_read on report_category_translations
for select using (true);

-- Reporter can read/insert their own reports.
create policy reports_self_read on reports
for select using (
  auth.uid() is not null
  and exists (
    select 1 from app_users u where u.id = reporter_id and u.auth_user_id = auth.uid()
  )
);

create policy reports_self_insert on reports
for insert with check (
  auth.uid() is not null
  and exists (
    select 1 from app_users u where u.id = reporter_id and u.auth_user_id = auth.uid()
  )
);

create policy report_attachments_self_read on report_attachments
for select using (
  exists (
    select 1
    from reports r
    join app_users u on u.id = r.reporter_id
    where r.id = report_id and u.auth_user_id = auth.uid()
  )
);

create policy report_attachments_self_insert on report_attachments
for insert with check (
  exists (
    select 1
    from reports r
    join app_users u on u.id = r.reporter_id
    where r.id = report_id and u.auth_user_id = auth.uid()
  )
);

create policy report_updates_self_read on report_updates
for select using (
  is_visible_to_user
  and exists (
    select 1
    from reports r
    join app_users u on u.id = r.reporter_id
    where r.id = report_id and u.auth_user_id = auth.uid()
  )
);

create policy report_status_history_self_read on report_status_history
for select using (
  exists (
    select 1
    from reports r
    join app_users u on u.id = r.reporter_id
    where r.id = report_id and u.auth_user_id = auth.uid()
  )
);

-- =====================================================================
-- Seed categories (4 minimums per CLAUDE.md)
-- =====================================================================

insert into report_categories (code, sort_order) values
  ('service', 10),
  ('security', 20),
  ('environment', 30),
  ('other', 90)
on conflict (code) do nothing;

insert into report_category_translations (category_id, locale, name)
select c.id, 'vi', case c.code
  when 'service' then 'Dịch vụ'
  when 'security' then 'An ninh trật tự'
  when 'environment' then 'Môi trường'
  when 'other' then 'Khác'
end
from report_categories c
on conflict do nothing;

insert into report_category_translations (category_id, locale, name)
select c.id, 'en', case c.code
  when 'service' then 'Service'
  when 'security' then 'Security & order'
  when 'environment' then 'Environment'
  when 'other' then 'Other'
end
from report_categories c
on conflict do nothing;
